experiment:
  name: fitnet_full_s1
  seed: 42
  device: cuda

data:
  root: ./dataset
  batch_size: 128
  num_workers: 4
  download: false
  pin_memory: true
  drop_last: false

training:
  epochs: 100
  learning_rate: 0.0005
  momentum: 0.9
  weight_decay: 5.0e-4

fitnet:
  hint_layers:
    - teacher_layer: layer1
      student_layer: layer1
      teacher_channels: 256
      student_channels: 64
    - teacher_layer: layer2
      student_layer: layer2
      teacher_channels: 512
      student_channels: 128
    - teacher_layer: layer3
      student_layer: layer3
      teacher_channels: 1024
      student_channels: 256
    - teacher_layer: layer4
      student_layer: layer4
      teacher_channels: 2048
      student_channels: 512

model:
  teacher_name: resnet50
  student_name: resnet18
  num_classes: 100
  pretrained_teacher: false
  teacher_weights_path: null
  teacher_checkpoint: ./experiments/checkpoints/teacher_finetune_cifar100/2026-05-10_19-43-05/teacher_finetune_cifar100_teacher_best.pt

checkpoint:
  dir: ./experiments/checkpoints

metrics:
  latency_num_batches: 50
  latency_warmup_batches: 5
